### ISSUE TITLE
Calling readJSON between reboots causes abort

### ISSUE THREAD

**Issue by rajsite** [ni/VireoSDK#275]
Static allocated string in EggShell_DataReadString and EggShell_DataWriteString is likely causing aborts() when Vireo is rebooted or re-run using a new user shell.

Possibly relevant source locations: 
   [Location where static string allocation occurs in scope of type manager reference?](https://github.com/ni/VireoSDK/blob/a8df6f39d23f04e55b05faf392260e3dcf17f8d2/source/core/CEntryPoints.cpp#L180)
   [Location where type manager reference is passed on call](https://github.com/ni/VireoSDK/blob/a8df6f39d23f04e55b05faf392260e3dcf17f8d2/source/io/module_eggShell.js#L140)
   [Location where type manager is deleted on reboot](https://github.com/ni/VireoSDK/blob/a8df6f39d23f04e55b05faf392260e3dcf17f8d2/source/io/module_eggShell.js#L118)

In the following example the first visit to endpoint eightball is successful and the second visit results in an abort.

This does not effect the vtr suite because it relies only on console io and not readJSON and writeJSON.
The karma test suite has had this issue before and the workaround is to create a new instance of the vireo runtime for every test.

In the express app creating a new runtime for every request slows response time by about 100ms (from 60ms sharing instances and just rebooting to 160ms creating a whole new instance)

```javascript
// server.js
// calls a web vi using the vireo runtime
// this example assumes the vi runs once per http request
// as such vireo is rebooted for every request

// init project
var express = require('express');
var app = express();
var fs = require('fs');

// load library to measure response time (optional)
var responseTime = require('response-time');
app.use(responseTime());

// load the Vireo Constructor Function
var Vireo = require('vireo');

// create a new Vireo instance
var vireo = new Vireo();

// register some logging functions (only used for debugging)
vireo.eggShell.setPrintFunction(console.log);
vireo.eggShell.setPrintErrorFunction(console.error);

// load the via source code
var via = fs.readFileSync('eightball.via.txt', "utf8");
var viName = 'Main%2Egviweb';

// http://expressjs.com/en/starter/static-files.html
app.use(express.static('public'));

// http://expressjs.com/en/starter/basic-routing.html
app.get("/", function (request, response) {
  response.sendFile(__dirname + '/views/index.html');
});

app.get("/eightball", function (request, response) {
  // reboot load the via code into the runtime
  vireo.eggShell.reboot();
  vireo.eggShell.loadVia(via);
  
  // take the input parameter of the query string and write it to the Input control
  var input = JSON.stringify(request.query.input);
  vireo.eggShell.writeJSON(viName, 'dataItem_Input', input);
  
  // run the via code and allow it to complete asynchronously
  (function runExecuteSlicesAsync() {
    var output;
    var status = vireo.eggShell.executeSlices(1000);
    
    if (status > 0) {
      setImmediate(runExecuteSlicesAsync);
    } else {
      output = JSON.parse(vireo.eggShell.readJSON(viName, 'dataItem_Output'));
      response.send(output);
    }
  }());
});
  
// listen for requests :)
var listener = app.listen(process.env.PORT, function () {
  console.log('Your app is listening on port ' + listener.address().port);
});
```

The via code
```
// Autogenerated Vireo assembly file
// Generated on 03/31/2017 11:57:28
define (g0 dv(a(.String *) ('It is certain' 'It is decidedly so' 'Without a doubt' 'Yes definitely' 'You may rely on it' 'As I see it, yes' 'Most likely' 'Outlook good' 'Yes' 'Signs point to yes' 'Reply hazy try again' 'Ask again later' 'Better not tell you now' 'Cannot predict now' 'Concentrate and ask again' 'Don\'t count on it' 'My reply is no' 'My sources say no' 'Outlook not so good' 'Very doubtful')))
//---------------------------------------------------
//VI Definition: Main.gviweb
define (Main%2Egviweb dv(.VirtualInstrument (
    Locals: c(   // Data Space1
        e(.Int32 local1)
        e(.Int32 local2)
        e(.Double local3)
        e(.Double local4)
        e(.Double local5)
        e(.Int32 local6)
        e(.String local7)
        e(dv(.String '')dataItem_Output)
        e(dv(.String '')dataItem_Input)
        e(.Double local10)
    )
        clump(1
        ArrayLength(g0 local1 )
        Decrement(local1 local2 )
        Convert(local2 local3)
        Random(local4 )
        Mul(local4 local3 local5)
        Convert(local5 local6)
        ArrayIndex(g0 local7 local6 )
        Copy(local7 dataItem_Output)
/* Clump Ended. */    )
)))
enqueue (Main%2Egviweb)
//Finished!! :D
```

output
```
//Allocations    3, AQCount    82, ShareTypes 0 (ES Delete end)
1:05 AM
5
1:05 AM
5
1:05 AM
abort(5) at Error
1:05 AM
    at jsStackTrace (/app/node_modules/vireo/dist/vireo.js:1:16679)
1:05 AM
    at stackTrace (/app/node_modules/vireo/dist/vireo.js:1:16862)
1:05 AM
    at abort (/app/node_modules/vireo/dist/vireo.js:17:7679)
1:05 AM
    at Array.CK (/app/node_modules/vireo/dist/vireo.js:10:81651)
1:05 AM
    at OB (/app/node_modules/vireo/dist/vireo.js:6:23654)
1:05 AM
    at hd (/app/node_modules/vireo/dist/vireo.js:9:48893)
1:05 AM
    at ccallFunc (/app/node_modules/vireo/dist/vireo.js:1:9506)
1:05 AM
    at /app/node_modules/vireo/dist/vireo.js:1:9812
1:05 AM
    at Object.Module.eggShell.readJSON.publicAPI.eggShell.readJSON [as readJSON] (/app/node_modules/vireo/source/io/module_eggShell.js:125:20)
1:05 AM
Jump to
at runExecuteSlicesAsync (/app/server.js:54:42)
1:05 AM
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
```

**Comment by rajsite** [comment]
Actually this is probably a duplicate of https://github.com/ni/VireoSDK/issues/163

**Comment by rajsite** [comment]
Woaaa found another workaround that is really fast for this use case of running the same VI repeatedly.

If we remove the enqueue(`some vi name`) from the via code then we can prevent the need for rebooting the runtime on every invocation altogether.

Instead before every execution we can just invoke loadVia('enqueue(Main%2Egviweb)') and then executeSlices until complete

Example times:
completely recreate vireo runtime, loadVia and executeSlices to finish: 130 - 160 ms
reboot the runtime, load via, and executeSlices to finish: 60 - 90 ms (causes error after first run right now)
calling loadVia('enqueue(Main%20gviweb)') and executeSlices to finish: 0.5 - 1 ms
